In [1]:
import pandas as pd
import numpy as np

print("Pandas:", pd.__version__)
print("NumPy:", np.__version__)

Pandas: 3.0.5
NumPy: 2.5.2

In [4]:
import pandas as pd

file_path = "../data/indian_ev_specs.csv"

# Read the malformed file line-by-line
with open(file_path, "r", encoding="utf-8") as f:
    lines = f.readlines()

# Remove the dataset title
lines = lines[1:]

# Clean newline characters
lines = [line.strip() for line in lines if line.strip()]

# Convert comma-separated lines into a DataFrame
rows = [line.split(",") for line in lines]

ev = pd.DataFrame(
    rows[1:],
    columns=rows[0]
)

# Convert numerical columns
numeric_cols = ["Price", "Range", "Power", "Battery"]

for col in numeric_cols:
    ev[col] = pd.to_numeric(ev[col], errors="coerce")

print("Shape:", ev.shape)
print("Columns:", ev.columns.tolist())

ev.head()

Shape: (26, 6)
Columns: ['Brand', 'Model', 'Price', 'Range', 'Power', 'Battery']

      Brand          Model  Price  Range  Power  Battery
0    Maruti  SuzukieVitara  15.99  440.0  142.0     49.0
1      Tata        PunchEV   9.69  275.0   87.0     30.0
2  Mahindra          XEV9e  21.90  542.0  228.0     59.0
3  Mahindra            BE6  18.90  557.0  228.0     59.0
4        MG      WindsorEV  14.00  332.0  134.0     38.0

In [3]:
print(ev.shape)
print(ev.columns.tolist())
ev.head()

(27, 1)
['ev_car_India_dataset 2']

                                         ev_car_India_dataset 2
Brand    Model         Price Range Power                Battery
Maruti   SuzukieVitara 15.99 440.0 142.0                   49.0
Tata     PunchEV       9.69  275.0 87.0                    30.0
Mahindra XEV9e         21.9  542.0 228.0                   59.0
         BE6           18.9  557.0 228.0                   59.0

In [5]:
print(ev.info())
print("\nMissing values:")
print(ev.isnull().sum())

print("\nDuplicate rows:")
print(ev.duplicated().sum())

<class 'pandas.DataFrame'>
RangeIndex: 26 entries, 0 to 25
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Brand    26 non-null     str
 1   Model    26 non-null     str
 2   Price    26 non-null     float64
 3   Range    26 non-null     float64
 4   Power    26 non-null     float64
 5   Battery  26 non-null     float64
dtypes: float64(4), str(2)
memory usage: 1.3 KB
None

Missing values:
Brand      0
Model      0
Price      0
Range      0
Power      0
Battery    0
dtype: int64

Duplicate rows:
0

In [6]:
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

# Features and target
X = ev[["Brand", "Model", "Range", "Power", "Battery"]]
y = ev["Price"]

# Categorical and numerical columns
categorical_features = ["Brand", "Model"]
numeric_features = ["Range", "Power", "Battery"]

# Preprocessing
preprocessor = ColumnTransformer(
    transformers=[
        ("cat", OneHotEncoder(handle_unknown="ignore"), categorical_features),
        ("num", "passthrough", numeric_features)
    ]
)

print("Features:", X.columns.tolist())
print("Target: Price")

Features: ['Brand', 'Model', 'Range', 'Power', 'Battery']
Target: Price

In [7]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("Training samples:", len(X_train))
print("Testing samples:", len(X_test))

Training samples: 20
Testing samples: 6

In [8]:
model = Pipeline(
    steps=[
        ("preprocessor", preprocessor),
        ("regressor", RandomForestRegressor(
            n_estimators=200,
            max_depth=8,
            random_state=42
        ))
    ]
)

model.fit(X_train, y_train)

print("Model trained successfully!")

Model trained successfully!

In [9]:
y_pred = model.predict(X_test)

mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2 = r2_score(y_test, y_pred)

print(f"MAE: ₹{mae:.2f} lakh")
print(f"RMSE: ₹{rmse:.2f} lakh")
print(f"R² Score: {r2:.3f}")

MAE: ₹10.64 lakh
RMSE: ₹14.67 lakh
R² Score: 0.590

In [10]:
sales = pd.read_csv("../data/pm_edrive_ev_sales.csv")

print("Shape:", sales.shape)
print("\nColumns:")
print(sales.columns.tolist())

sales.head(10)

Shape: (37, 5)

Columns:
['Sl. No.', 'State/UT', 'e-2W', 'e-3W', 'Total']

  Sl. No.                     State/UT   e-2W     e-3W  Total
0       1  Andaman and Nicobar Islands     17      NaN     17
1       2               Andhra Pradesh  39331   2640.0  41971
2       3            Arunachal Pradesh     18      NaN     18
3       4                        Assam   2464  12111.0  14575
4       5                        Bihar  13672  10136.0  23808
5       6                 Chhattisgarh  24193   2393.0  26586
6       7                   Chandigarh   1220    140.0   1360
7       8                Daman and Diu    130      8.0    138
8       9                        Delhi  19704   3433.0  23137
9      10                          Goa   6421     17.0   6438

In [13]:
df = pd.read_csv("../data/indian_ev_specs.csv", skiprows=1)

print("Shape:", df.shape)
print("Columns:", df.columns.tolist())

display(df.head())

Shape: (26, 6)
Columns: ['Brand', 'Model', 'Price', 'Range', 'Power', 'Battery']

      Brand          Model  Price  Range  Power  Battery
0    Maruti  SuzukieVitara  15.99  440.0  142.0     49.0
1      Tata        PunchEV   9.69  275.0   87.0     30.0
2  Mahindra          XEV9e  21.90  542.0  228.0     59.0
3  Mahindra            BE6  18.90  557.0  228.0     59.0
4        MG      WindsorEV  14.00  332.0  134.0     38.0

In [14]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

file_path = "../data/indian_ev_specs.csv"

# Read the CSV
df = pd.read_csv(file_path, skiprows=1)

# Make sure numeric columns are numeric
numeric_cols = ["Price", "Range", "Power", "Battery"]

for col in numeric_cols:
    df[col] = pd.to_numeric(df[col], errors="coerce")

print("✅ Dataset loaded")
print("Shape:", df.shape)
print("Columns:", df.columns.tolist())

display(df.head())

✅ Dataset loaded
Shape: (26, 6)
Columns: ['Brand', 'Model', 'Price', 'Range', 'Power', 'Battery']

      Brand          Model  Price  Range  Power  Battery
0    Maruti  SuzukieVitara  15.99  440.0  142.0     49.0
1      Tata        PunchEV   9.69  275.0   87.0     30.0
2  Mahindra          XEV9e  21.90  542.0  228.0     59.0
3  Mahindra            BE6  18.90  557.0  228.0     59.0
4        MG      WindsorEV  14.00  332.0  134.0     38.0

In [15]:
print("Missing values:")
print(df.isnull().sum())

print("\nDuplicates:", df.duplicated().sum())

Missing values:
Brand      0
Model      0
Price      0
Range      0
Power      0
Battery    0
dtype: int64

Duplicates: 0

In [16]:
X = df[["Brand", "Range", "Power", "Battery"]]
y = df["Price"]

categorical_features = ["Brand"]
numeric_features = ["Range", "Power", "Battery"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

preprocessor = ColumnTransformer(
    transformers=[
        (
            "brand",
            OneHotEncoder(handle_unknown="ignore"),
            categorical_features
        )
    ],
    remainder="passthrough"
)

model = Pipeline(
    steps=[
        ("preprocessor", preprocessor),
        (
            "regressor",
            RandomForestRegressor(
                n_estimators=300,
                max_depth=5,
                random_state=42
            )
        )
    ]
)

model.fit(X_train, y_train)

print("✅ Random Forest model trained!")

✅ Random Forest model trained!

In [17]:
predictions = model.predict(X_test)

mae = mean_absolute_error(y_test, predictions)
rmse = np.sqrt(mean_squared_error(y_test, predictions))
r2 = r2_score(y_test, predictions)

print(f"MAE: ₹{mae:.2f} lakh")
print(f"RMSE: ₹{rmse:.2f} lakh")
print(f"R² Score: {r2:.3f}")

MAE: ₹10.43 lakh
RMSE: ₹14.56 lakh
R² Score: 0.596

In [18]:
from sklearn.model_selection import KFold, cross_val_score

cv = KFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

print("5-fold cross-validation created.")

5-fold cross-validation created.

In [19]:
cv_mae = -cross_val_score(
    model,
    X,
    y,
    cv=cv,
    scoring="neg_mean_absolute_error"
)

cv_r2 = cross_val_score(
    model,
    X,
    y,
    cv=cv,
    scoring="r2"
)

print(f"Cross-validation MAE: ₹{cv_mae.mean():.2f} lakh")
print(f"Cross-validation MAE std: ₹{cv_mae.std():.2f} lakh")
print(f"Cross-validation R²: {cv_r2.mean():.3f}")
print(f"Cross-validation R² std: {cv_r2.std():.3f}")

Cross-validation MAE: ₹7.33 lakh
Cross-validation MAE std: ₹3.87 lakh
Cross-validation R²: 0.699
Cross-validation R² std: 0.229

In [20]:
gradient_model = Pipeline(
    steps=[
        ("preprocessor", preprocessor),
        (
            "regressor",
            GradientBoostingRegressor(
                n_estimators=100,
                learning_rate=0.05,
                max_depth=2,
                random_state=42
            )
        )
    ]
)

gradient_model.fit(X_train, y_train)

gradient_pred = gradient_model.predict(X_test)

gradient_mae = mean_absolute_error(y_test, gradient_pred)
gradient_rmse = np.sqrt(mean_squared_error(y_test, gradient_pred))
gradient_r2 = r2_score(y_test, gradient_pred)

print(f"Gradient Boosting MAE: ₹{gradient_mae:.2f} lakh")
print(f"Gradient Boosting RMSE: ₹{gradient_rmse:.2f} lakh")
print(f"Gradient Boosting R²: {gradient_r2:.3f}")

Gradient Boosting MAE: ₹10.55 lakh
Gradient Boosting RMSE: ₹15.04 lakh
Gradient Boosting R²: 0.569

In [21]:
results = pd.DataFrame({
    "Model": [
        "Random Forest",
        "Gradient Boosting"
    ],
    "MAE": [
        mae,
        gradient_mae
    ],
    "RMSE": [
        rmse,
        gradient_rmse
    ],
    "R2": [
        r2,
        gradient_r2
    ]
})

results

               Model        MAE       RMSE        R2
0      Random Forest  10.434730  14.555696  0.596389
1  Gradient Boosting  10.552864  15.041812  0.568980

In [22]:
import joblib
import os

os.makedirs("../ml", exist_ok=True)

joblib.dump(model, "../ml/ev_price_model.pkl")

print("✅ Random Forest model saved!")
print("📁 Location: ml/ev_price_model.pkl")

✅ Random Forest model saved!
📁 Location: ml/ev_price_model.pkl

In [23]:
loaded_model = joblib.load("../ml/ev_price_model.pkl")

print("✅ Model loaded successfully!")

✅ Model loaded successfully!

In [24]:
test_ev = pd.DataFrame({
    "Brand": ["Tata"],
    "Range": [450],
    "Power": [150],
    "Battery": [45]
})

predicted_price = loaded_model.predict(test_ev)[0]

print(f"Estimated Price: ₹{predicted_price:.2f} lakh")

Estimated Price: ₹17.91 lakh